In [5]:
import numpy as np

Creating numpy arrays from python lists

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
np.array([1,2,3,4], dtype=('float32'))

array([1., 2., 3., 4.], dtype=float32)

In [17]:
a1=np.array([1,2,3])

In [19]:
type(a1)

numpy.ndarray

In [21]:
a2 = np.array([[1,2,3],[4,5,6]])

In [22]:
type(a2)

numpy.ndarray

In [23]:
a2.shape

(2, 3)

In [24]:
a2.ndim

2

In [25]:
a2.dtype

dtype('int64')

In [26]:
a2.size

6

Creating numpy arrays from scratch
zeros, ones, full, arange, linspace

In [32]:
np.zeros((2,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.ones((2,4),dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
np.full((3,5),6.8)

array([[6.8, 6.8, 6.8, 6.8, 6.8],
       [6.8, 6.8, 6.8, 6.8, 6.8],
       [6.8, 6.8, 6.8, 6.8, 6.8]])

In [41]:
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

random

In [46]:
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [45]:
np.random.random((4,4))

array([[0.86372347, 0.90820438, 0.30572795, 0.21989379],
       [0.72417876, 0.7811525 , 0.71935591, 0.23395582],
       [0.04987885, 0.64715842, 0.5218934 , 0.50820433],
       [0.60978969, 0.58428697, 0.95784437, 0.25892887]])

In [48]:
np.random.normal(0,1,(3,3))

array([[ 1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462]])

In [49]:
np.random.randint(3,10,(3,3))

array([[3, 7, 8],
       [8, 9, 3],
       [7, 4, 7]])

In [51]:
np.random.rand(4,4)

array([[0.31823351, 0.85877747, 0.45850317, 0.44458729],
       [0.33610227, 0.88067812, 0.94502678, 0.99189033],
       [0.37674127, 0.96614745, 0.79187957, 0.67568915],
       [0.24488948, 0.21645726, 0.16604782, 0.92275661]])

Indexing và Slicing

In [52]:
x1 = np.random.randint(20,size = 6)

In [53]:
x1

array([15, 17,  6,  0,  6, 12])

In [55]:
x1[4], x1[0], x1[-1]

(6, 15, 12)

In [57]:
x2 = np.random.randint(30, size = (3,4))

In [58]:
x2

array([[22, 15, 10,  2],
       [ 8,  6, 22, 21],
       [ 2, 21,  0, 10]])

In [61]:
x2[1,2]=6

In [62]:
x2

array([[22, 15, 10,  2],
       [ 8,  6,  6, 21],
       [ 2, 21,  0, 10]])

In [63]:
x1[0:3]

array([15, 17,  6])

In [64]:
x1 [::2]

array([15,  6,  6])

In [65]:
x2[:2,:3]

array([[22, 15, 10],
       [ 8,  6,  6]])

In [66]:
x2[:,:2]

array([[22, 15],
       [ 8,  6],
       [ 2, 21]])

Reshape và Transpose

In [72]:
grid = np.arange(1,10)
grid.shape

(9,)

In [73]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
x=np.array([1,2,3])

In [78]:
x.reshape(1,3).shape

(1, 3)

In [79]:
x

array([1, 2, 3])

In [87]:
y = np.array([[1,2],[4,5]])

In [91]:
y.T

array([[1, 4],
       [2, 5]])

Concatenation và Splitting

In [94]:
x=np.array([[1,2,3]])
y=np.array([[4,5,6]])

In [97]:
np.concatenate((x,y),0)

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
grid = np.array([[1,2,3]
                ,[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.concatenate((grid,grid),1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [107]:
#vstack
x = np.array([1,2,7])
y = np.array([[6,2,3]
            ,[4,5,8]])
np.vstack((x,y))

array([[1, 2, 7],
       [6, 2, 3],
       [4, 5, 8]])

In [110]:
#hstack
x = np.array([1,2,7])
y = np.array([6,2,3])
np.hstack((x,y))

array([1, 2, 7, 6, 2, 3])

In [112]:
x= np.array([1,2,4,55,43,31,23,23,32])

In [115]:
x1, x2, x3 = np.split(x,[2,6])

In [117]:
x1, x2, x3

(array([1, 2]), array([ 4, 55, 43, 31]), array([23, 23, 32]))

Broadcasting và Vectorised Operations

In [119]:
a= np.arange(3)

In [123]:
#broadcasting
a +5

array([5, 6, 7])

In [125]:
b= np.ones((3,3))

In [128]:
a.shape, b.shape

((3,), (3, 3))

In [129]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [130]:
a*b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

manipulate & compare Numpy Array

#aggregation

In [132]:
list_number = [1,2,3,4]

In [133]:
ll = np.array(list_number)

In [134]:
ll

array([1, 2, 3, 4])

In [135]:
sum(ll) #python

10

In [136]:
np.sum(ll) #nhanh hon

10

In [142]:
#create massive numpy array 
massive_array = np.random.random(10000)
massive_array[:5]
massive_array.shape

(10000,)

In [144]:
%timeit sum(massive_array) #python built in funtion
%timeit np.sum(massive_array) #numpy 

705 µs ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.25 µs ± 90.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [145]:
np.mean(massive_array)

0.49707455616169527

In [146]:
np.max(massive_array)

0.9998042215863371

In [148]:
dog_height = [600,470,170,430,300]
dog_height = np.array(dog_height)

In [149]:
np.std(dog_height) #do lech chuan

147.32277488562318

In [150]:
np.var(dog_height) #phuong sai

21704.0

In [151]:
np.sqrt(np.var(dog_height))

147.32277488562318

Sorting arrays

In [152]:
x = np.array([1,2,6,34,32,23,66,55])
np.sort(x)

array([ 1,  2,  6, 23, 32, 34, 55, 66])

In [154]:
np.argsort(x)

array([0, 1, 2, 5, 4, 3, 7, 6])

#sorting rows and columns

In [159]:
np.random.seed(42)
mata = np.random.randint(0,10,size = (4,6))
mata

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [162]:
np.sort(mata,1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

linear algebra

In [164]:
a= np.array([[1,2,3],[44,55,44],[12,43,21]])

In [173]:
b=np.array([[1,3],[3,3],[4,5]])
b

array([[1, 3],
       [3, 3],
       [4, 5]])

In [179]:
a.dot(b)

array([[ 19,  24],
       [385, 517],
       [225, 270]])

In [180]:
a @ b

array([[ 19,  24],
       [385, 517],
       [225, 270]])

In [181]:
b.T @ a

array([[181, 339, 219],
       [195, 386, 246]])

dot product 

In [182]:
np.random.seed(0)
sales_amount = np.random.randint(20, size = (5,3))

In [183]:
import pandas as pd

In [184]:
weekly_sales = pd.DataFrame(sales_amount,
                            index=['mon','tue','wed','thu','fri'], columns = ['pizza','ice_cream','noodle'])

In [185]:
weekly_sales

pizza  ice_cream  noodle
mon     12         15       0
tue      3          3       7
wed      9         19      18
thu      4          6      12
fri      1          6       7

In [190]:
price = np.array([[6,2,5]])

In [191]:
price

array([[6, 2, 5]])

In [193]:
price_food = pd.DataFrame(price.reshape(1,3),index=['price'],columns = ['pizza','ice_cream','noodle'])
price_food

pizza  ice_cream  noodle
price      6          2       5

In [195]:
weekly_sales.shape, price_food.shape

((5, 3), (1, 3))

In [198]:
total = weekly_sales @ price_food.T
total

price
mon    102
tue     59
wed    182
thu     96
fri     53

In [199]:
weekly_sales["total"]= total
weekly_sales

pizza  ice_cream  noodle  total
mon     12         15       0    102
tue      3          3       7     59
wed      9         19      18    182
thu      4          6      12     96
fri      1          6       7     53